sudo: false
language: rust
rust:
 - stable
 - beta
 - nightly
matrix:
  allow_failures:
   - rust: nightly
addons:
  apt:
    packages:
     - unixodbc
     - unixodbc-dev
     - odbc-postgresql
     - libsqliteodbc
services:
 - postgresql
before_script:
 - psql -c 'create database travis_ci_test;' -U postgres
 - psql -d travis_ci_test -f travis/setup.sql
 - export ODBCINI=${PWD}/travis/odbc.ini
script:
  - cargo build --release
  - cargo test --verbose --release --features travis
  - cargo doc --no-deps
env:
 - global:
   - RUST_BACKTRACE=1