sudo: false
language: rust
rust:
 - stable
 - beta
 - nightly
matrix:
  allow_failures:
   - rust: nightly
addons:
  apt:
    packages:
     - unixodbc
     - unixodbc-dev
     - odbc-postgresql
     - libsqliteodbc
services:
 - postgresql
before_script:
 - psql -c 'create database travis_ci_test;' -U postgres
 - export ODBCINI=${PWD}/travis/odbc.ini
 - cargo install cargo-travis
 - export PATH=$HOME/.cargo/bin:$HOME/.local/bin:$PATH
script:
 - cargo test --verbose
env:
 - global:
   - RUST_BACKTRACE=1